BharatNavNirmanWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BharatNavNirmanWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
           return View();
        }
        public ActionResult दूरदर्शिता_और_मिशन()
        {
            return View();
        }
        public ActionResult भारत_दर्शन()
        {
            return View();
        }
        public ActionResult भारतीय_संविधान()
        {
            return View();
        }
        public ActionResult राजनीति_संयोजन()
        {
            return View();
        }
        public ActionResult पुस्तकालय()
        {
            return View();
        }

        public ActionResult योजना()
        {
            return View();
        }
        public ActionResult सूचना_खिड़की()
        {
            return View();
        }
        public ActionResult सेवा_खिड़की()
        {
            return View();
        }
        public ActionResult प्रकाशन()
        {
            return View();
        }
        public ActionResult आवेदन_प्रपत्र()
        {
            return View();
        }
        public ActionResult आइकॉन()
        {
            return View();
        }  
        public ActionResult सूचना_का_अधिकार()
        {
            return View();
        }
    }
}

BharatNavNirmanWeb/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BharatNavNirmanWeb.Controllers
{
    public class MapController : Controller
    {
        public ActionResult भारत_का_मानचित्र()
        {
            return View();
        }
    }
}

BharatNavNirmanWeb/Controllers/QuestionAnswerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BharatNavNirmanWeb.Controllers
{
    public class QuestionAnswerController : Controller
    {
        // GET: QuestionAnswer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult QuestionMaster()
        {
            return View();
        }

        public ActionResult ResponseMaster()
        {
            return View();
        }
    }
}

BharatNavNirmanWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "भारत नव निर्माण ";
}

<h2>@ViewBag.Title.</h2>
<link href="~/fonts/FontStyle.css" rel="stylesheet" />

<p class="customeFont" style="font-weight:bold;width:400px;margin-left:300px;">
    ^^fopkjksa ls cM+k D;k gks ldrk gS \ gekjh lksp ls cM+k D;k gks ldrk gS \ gekjs /;ku ls cM+k D;k gks ldrk gS \ gekjs mn~ns';ksa ls cM+k D;k gks ldrk gS \ gekjs vkn'kksZa ls cM+k D;k gks ldrk gS \ gekjh mM+kuksa ls cM+k D;k gks ldrk gS \ D;k mUeqDr xxu esa mM+us ds fy, ia[k t:jh gS \ D;k tehu ij pyus ds fy, lgkjs dh t:jr gS \ vkf[kj gesa D;k&D;k t:jr gS \ ;s dkSu crk;sxk] bl jaxHkwfe ij \**
</p>
<p class="customeFont">
    vki lHkh dk Hkkjr uo fuekZ.k esa Lokxr~ djrk gw¡A vkidk ekxZn'kZu gh Hkkjr uo fuekZ.k fotu 2020 gSA Hkkjr uo fuekZ.k ,d lksp gS] fopkj gS] le> gS] mRFkku gS------------ xk¡o] iapk;r] iz[k.M] vuqe.My] uxj] ftyk] ize.My] jkT; rc jk"Vª fuekZ.k ds lkFk lekt fuekZ.k gSA eSaus tks eglwl fd;k] mlh dks O;Dr dj jgk gwWA vki lHkh ds lg;ksx ls vius tUeHkwfe] deZHkwfe ,oa jk"V~Hkwfe ds fy, dqN djus dh bPNk tks yacs le; ls jgh gS mls vc /kjkry ij nks dne c<+kus dk le; vk x;k gSA
</p>
<p class="customeFont" style="font-weight:bold;">Jh jke us y{e.k ls dgk Fkk &^^vfi Lo.kZe;h yadk u jkspus y{e.k%A
                       Tkuuh tUeHkwfe'p LoxkZnfi xjh;flAA**
</p>
<p class="customeFont" >
    vFkkZr~ gs y{e.k eq>s lksus dh yadk vPNh ugha yxrh gS ekrk vkSj ekr`Hkwfe LoxZ ls Hkh cgSaA
</p>
<p class="customeFont" style="font-style:italic;">
    dgus dks rks lkjh rkdr fo/kkf;dk] dk;Zikfydk ,oa U;k;ikfydk esa fufgr gS] ijarq ;FkkFkZ esa dk;Zikfydk esa gh iwjk lafo/kku fufgr gSA laln ;kfu yksdlHkk esa cSBs lkalnksa ij gh iwjs ns'k dh fuxkgsa fVdh gqbZ jgrh gSA ysfdu vktknh ds brus lkyksa ckn Hkh ge bu eqn~nksa ij >xM+us dks rS;kj gksrs gaS fd lafo/kku fuekZrk dkSu Fks] ijarq vke vkneh ds fy, cgqr gh de cgl dh txg jg xbZ gS gekjs laln esaA vxj gekjk lafo/kku iw.kZr% lgh gh gS rks vkt rd gq, la'kks/kuksa ls gekjs fuekZrkvksa dk vieku gh ekuk tkuk pkfg,A vxj ugha rks ;s le; ds lkFk cnyko dh vko';drk ekax gh gS rks gekjs lafo/kku esa iw.kZr% cnyko gksuh gh pkfg, ;kfu lafo/kku esa la'kks/ku ugha iw.kZr% cnyus dh ckr Hkh j[kh tk ldrh gSA vc le; vk x;k gS fd gekjs laln esa cSBs lkaln ns'k dh turk ds fglkc ls lafo/kku cuk;s vkSj la'kks/ku djsa ;k iw.kZ lafo/kku cnyus ij fopkj djsaA lafo/kku ls ns'k pyrk gS uk fd lkaln ,oa tuizfrfuf/k;ksa lsA gekjs ns'k ds lapkyd ;s le> cSBs gS fd lapkyu dk vk/kkj gekjs esa gh fufgr gSA vke vkneh ds lksp ,oa mldh fopkjksa ls mudk dksbZ okLrk ugha gksrk gSaA vktknh ds 70 osa lky esa Hkh ge xqyke gaS] ns'k ds Hkz"Vkpkjh lekt ls] jktusrkvksa ls] Hkz"V iztk ikydksa ls] ix&ix ij] ul&ul esa vR;kpkj Hkjk iM+k gSA lafo/kku iwjs fo'o ls ysdj cukus dk mn~ns'; ;g Fkk fd rRdkyhu ifjos'k esa ns'k dks lapkyu dk ewy vk/kkj fey ldsA ysfdu ifjorZu ;k la'kks/ku dh cgqr lkjh ;k ;w¡ dgk tk;s rks yxHkx lafo/kku gh cnyuk vc t:jh eglwl gks jgk gSA ckj&ckj ckrsa vkrh gS fd cnyko gks] lRrk ifjorZu gsk] gj rjhds ds gFkd.Ms viuk;s tkrs gS Hkkjrh; jktuhfr esa] ftlls uqdlku flQZ ns'kokfl;ksa dks gS tks iw¡thifr ugha gSaA
</p>
<p class="customeFont" >
    ;gh ij Mk0 txUukFk feJ (iwoZ eq[;ea=h] fcgkj) th fd iafDr ls cgqr lkjh ckrsa Li"V gks tkrh gS fd & 
</p>
<p class="customeFont" style="font-weight:bold;width:400px;margin-left:300px;">
    ^^lafo/kku dh ea'kk ;gha Fkh fd ljdkjh izfdz;k lkekftd&vkfFkZd vlekurkvksa ds mRrjksRrj ?kVkus jgus okyh gksA laoS/kkfud vkSj dkuwu pykus okyh ,tsafl;k¡ ftUgsa gkfl;s ds leqnk;ksa ds vf/kdkjksa dks lqj{kk iznku djus dk nkf;Ro lkSaik x;k] ;Fks"B lgk;rk iznku djus esa vlQy jgha gSA**
</p>
<p class="customeFont" >
    xr o"kksZa esa ppkZ dk fo"k; jgk gS Hkkjrh; jktuhfrA vkf[kj Hkkjrh; jktuhfr esa okdbZ ,slh dkSu lh [kkl ckrsa gS ftlij 2011 ls fo'kky ppkZ py iM+hA fiNys ik¡p n'kdksa esa tUe fy;s yksxksa esa lcls cM+k vkanksyu vUuk vkanksyu gh ns[kk gksxkA mlh le; ls ,d ubZ dok;r 'kq: gqbZ vkSj tUe gqvk ubZ lkekftd Lo:Ik dkA vkf[kj yksxksa dk xqCckj 42 lkyksa ckn fQj QwVkA uo;qodksa }kjk ts-ih- vkanksyu dks lQy cuk;k x;kA ifjorZu rks gqvk] ysfdu iFk ogh jgk tks yxkrkj lfn;ksa ls pyh vk jgh gSA vkt gj O;fDr ifjorZu pkgrk gS] dksbZ [kq'k ugha gS] pkgsa oks bl ns'k ds egkefge jk"Vªifr gks] iz/kkuea=h gks] eq[;ea=h gks ;k gks ,d iapk;r ds eqf[k;kA tuizfrfuf/k;ksa esa gh O;fDrxr Lora=rk ,oa dRrZO;fu"Bk dh deh gSA gj dksbZ ,d nwljs ij gh nks"kkjksi.k esa O;Lr gS] rks vkf[kj dSls cusxk Hkkjr fodflr jk"Vª\ ftl jk"Vª dks xkSjoiw.kZ yksdra= dh LFkkiuk dk tud ekuk tkrk gS mls ge vkt cpkus esa vlgt eglwl dj jgs gSA bl ns'k esa lafo/kku dh bruh 'kk[kk,¡ gS ftldh fxurh vPNs&vPNs tkudkjksa ds fy, Hkh eqf'dy gSaA bl o"kZ ge lHkh vktknh dk 70 ok¡ fnol eku;sxsa] ijarq vkt rd ge lHkh ,d uk gks lds gaSA vktknh ds 70 lky ckn Hkh gekjs ns'k ds jktusrk ;g ugha dg ldrs fd geus ,d {ks= dks fodflr dj fn;kA bl ns'k ds gj vPNs cqjs dke ds fy, flQZ jktusrk gh ftEesokj gS vkSj dksbZ ughaA ns'k ds lapkyu dh ftEesokjh bu usrkvksa us [kqn gh vius ikl j[k yh gSA vktknh ij jkst cgl py jgh gS jk"Vªh; pSuyksa ij fnu izfrfnu ;gh jkx gSA gj dksbZ cksyus dh Lora=rk dks gh Lora= ekurs gaSA gekjh vktknh dks dkxtksa rd gh lhfer j[kk x;k gS vkSj vius gks'k laHkkyus ls ysdj vkt rd tks jktuhfr geus ns[kk oks cgqr gh nq%[kn gS] lkFk gh d"V dj HkhA
</p>
<p class="customeFont" style="font-weight:bold;">
    dfo ukxktqZu us dgk gS&
</p>
<p class="customeFont" >^^mij &mij ih tkrs gSa tks ihusokys gSaA<br />
dgrs gSa ,sls txrh esa tks thus okys gSaAA**
</p>

<p class="customeFont" >lokyksa ls f?kjh ;s ftanxh] gesa mUeqDr xxu esa mM+us ls jksdrh gSA gj dksbZ tUe fy;k gS] cpiu fcrk;s gaS] cM+s gksus ds lkFk&lkFk reke rfjdkas ds vuqHko feys gksxsa ,oa jkst feyrs jgrs gaSA gj dksbZ lqcg mBdj viuh vPNh lqcg dh dkeuk djrk gS] ysfdu viuksa ds pDdj esa ge fdruksa ds psgjs ls tkus&vutkus [kqf'k;kW fNu ysrs gSaA bldk vuqHko djuk ,oa eglwl djuk gh cM+k dfBu gS] ysfdu dHkh 'kkafr ds nks&iy feys rks t:j ;kn vkrk gS fd geus D;k ik;k vkSj D;k vkSj ik ldrs Fks mldh v/kwjh vkdka{kk eu esa gh jg tkrh gSA fQj Hkh 'kq: ls ftl rjhdksa ls lekt dk fuekZ.k fd;k x;k mlh esa ifjorZu dj le;&le; ij ,d u;k fe'kky rS;kj fd;k tkrk gS tks ,d lq[kn vuqHko ek= gh gksrk gSA vkt tks eSa ckr djus tk jgk gwW oks D;k gS oks rks vkids vkSj gekjs chp dk ,d ,slk laokn tks u;s Hkkjr fuekZ.k esa ,d ubZ Hkkxhnkjh ds lkFk 'kq: gksxhA lekt fuekZ.k dh ftEesokjh fdlh dks fn;k ugha tk ldrk] mls rks vius vki gh ysdj pyuk iM+rk gSA vkt lks'ky fefM;k gh cktkj ds egRo dks ekU;rk nsrh gS ,oa lekt dk :[k cnyus dh iwjh rkdr j[krh gSA ysfdu oks Hkh rc tc lekt esa lfdz;rk dh Hkwfedk fuHkkus dh rkdr fdlh esa gksA gj dksbZ vkxs c<+uk pkgrk gS] ysfdu igys dkSu \ bl pDdj esa cgqr nsj gks tkrh gS vkSj ge oDr ,oa lekt dks nks"kh Bgjk nsrs gSA ysfdu le; dks vius lkFk ysdj Hkkjr uo fuekZ.k dh ckr djsa vkSj izR;sd O;fDr dh Hkwfedk lc feydj lqfuf'pr djsaA
</p>
<p class="customeFont" >blhfy, rks jk"Vªdfo fnudj th us fy[kk gS fd &
</p>
<p class="customeFont" style="font-weight:bold;width:400px;margin-left:300px;">
    ^^[kkuksa dks feyrk nw/k oL=] Hkw[ks ckyd vdqykrs gSa]
    ek¡ dh gM~Mh ls fpid fBdqj] tkM+s dh jkr fcrkrs gSaA
    vfLFk dh yTtk clu csap] tc C;kt pqdk, tkrs gS]
    ekfyd rc rsy Qqysyksa ij] ikuh&lk nzO; cgkrs gSaAA**

</p>
<p class="customeFont" >
    cpiu ls ;g ns[krs vk;s gS fd lekt dks fn'kk nsus okyk dksbZ ,d gksrk gS ,oa mlh ds lgkjs lc viuh viuh uS;k ikj yxk ysrs gSA blh dh otg ls vkt rd pan yksxksa }kjk usr`Rofoghu lekt dk Lo:i cuk fn;k x;k gSA bls eglwl djrs gq, gh vkt eSa ^^Hkkjr uo fuekZ.k** ds ek/;e ls viuh ckr j[k jgk gwW] ftls fo}rtuksa }kjk ekxZnf'kZr fd;k x;k gSA vki lHkh ,oa [kkl dj u;s ih<+h ls dguk pkgrk gwW fd tc ge cpiu esa Fks rks tkr&ikr] mWp&uhp] NksVk&cM+k dk dksbZ Hkh Hkko eu esa ugha vk;k gksxkA 'kk;n eSa tgkW ls lksp jgk gwW oks ;FkkFkZ ds djhc ls gh xqtjrh gSA vkt Hkh ubZ ihf<+;ksa esa ;s ckr dgha uk dgha [kyrh gh gS fd ge fdl ;qx esa gS vkSj fdl rjg th;s tk jgs gSA
</p>
<p class="customeFont" >D;k ,d ,sls Hkkjr dk fuekZ.k ge ugha dj ldrs] tgkW okdbZ esa nks twu dh jksVh ds fy, fdlh dks tw>uk uk iM+s\ fdlh dks nks tksM+h diM+ksa ds fy, uk lkspuk--------------------------------------
</p>
<p class="customeFont" >
    dfo Mk0 egs'k jk; dh iafDr pfjrkFkZ gks jgh gS % &
</p>
<p class="customeFont" style="font-weight:bold;width:400px;margin-left:300px;">
    ^^tks Hkh Fkh eksVh dqVh vkSj eksVh gks xbZ]
    tks Hkh Fkh NksVh dqVh vkSj NksVh gks xbZA
    ckWVus okys dkSu lh yh gS rjktw gkFk esa]
    ikbZ rks iSlk cuh] /kksrh yxkSVh gks xbZ AA**
</p>
<p class="customeFont" >
    vkf[kj vkt rd ,d ,slh iz.kkyh fodflr ugha dh tk ldh ftlls iwjk Hkkjr cM+s vklkuh ls lapkfyr gks ldsA gj vkneh ds ikl Hkj isV Hkkstu] ru <dus ds fy, diM+k] lj ij ,d Nr gks ,d edku gks ;g lqfuf'fpr ugha dj ik;s gSA vkt gj ikVhZ pkgs oks dkaxzsl gks ;k chtsih ns'k Lrj ij ,oa {ksf=; Lrj ij NksVh eksVh ikfVZ;k¡] lc>wB dh [ksrh esa O;Lr gS vkSj ns'k ds eq[; m|ksxifr fdlkuksa ,oa ;qokvksa dh cfy p<+k jgh gSA bl ns'k dks fdlh Hkh pht dks fons'k ls ykus dh t:jr gh ugha iM+rh vxj fdlkuksa vkSj ;qokvksa dks leqfpr lqfo/kk eqgS;k djk;k tkrkA
</p>
<p class="customeFont" style="font-family:Arial;font-style:italic;font-weight:bold;">
    “Agriculture is the backbone of the Indian Economy"- said Mahatma Gandhi six decades ago.”
</p>
<p class="customeFont" >
    la;qDr ifjokj D;ksa VqV jgsa gS] bl dk dkj.kdh t:jr ugha gS] cfYd mUgsa latksx dj j[kus dh t:jr gSA ,d Lo:Ik esa lekt dk u;k fuekZ.k djus ij fopkj djus dh t:jr gSA tc vius vki dks ilan ugha djrs gS uk] rks vius ls tqM+h gqbZ dksbZ pht vPNh ugha yxrh gSA ubZ phtsa vkdf"kZr djrh gSa] tc vius vkidks I;kj djus yxrs gSa rks ogh iqjkuh ftnaxh] ubZ yxus yxrh gS] vPNh yxus yxrh gSA ,d vthc lh /kkjk ns'k esa py iM+h gS] fd gesa lrk;k x;k] rks gesa vkj{k.k pkfg,] fdlus lrk;k vkSj D;ksa lrk;k ;g dksbZ bl /kjrh ij Li"V ugha dj ldrk gSA oSpkfjd le> blh esa gS fd ge lHkh vkt ds Hkkjr dks cuk;s uk fd xqykeh ds yxHkx 1500 o"kksZa dks ysdj ge vkil esa gh yM+saA bl vk;kZorZ ds uk tkus fdrus VqdM+s gks pqds gS vkSj vkt Hkh ge vius ?kj dh cckZnh ds fy, [kqn gh ftEesokj gSA
</p>
<p class="customeFont" >
    egkdfo jk"Vªdfo] fo'o dfo] lkfgRdkj iks:"k vkSj ikod] tokuh vkSj [kkuh] mtkZ vkSj meax ds i;kZ; jke/kkjh flag fnudj us dgk gS &
</p>
<p class="customeFont" style="font-weight:bold;width:400px;margin-left:300px;">
    ^^lej 'ks"k gS ugha iki dk Hkkxha dsoy O;k/kA
      tks rVLFk gS le; fy[ksxk] mldk Hkh vijk/kAA
       vkSj Hkh
        vU;k; ldgj cSB jguk] ;g egknq"deZ gSA
    U;k;kFkZ vius ca/kqvksa dks naM nsuk /keZ gSAA**
</p>
<p class="customeFont" >
    bl ns'k esa fdlh Hkh ckrksa] dkeksa ds fy, ftEesokj vkf[kj dkSu\ ;s loky cM+k gksrk tk jgk gS] ns'k esa cM+s ls cM+s inksa ij cSBs yksxksa dks viuh ftEesokjh dk ,sglkl gh ugha gSA tks xyr ns[kdj] vk¡[ksa uk Qsjs] oks le; dc vk;sxk] vkSj dc gekjs fy, bl ns'k dk lafo/kku] iqfyl iz'kklu dk;Z djsxkA lc dqN fl[kk;k tk ldrk gS ijarq fdlh fd Hkkoukvksa dh dnj dSls djsa ;s dkSu fl[kk;sxkA bl Hkkjr ekrk dh dnj dSls djsa oks dkSu fl[kk;sxk\\\\\
</p>
<p class="customeFont" >
    blh fuekZ.k dh nwljh dM+h esa Hkkjr uo fuekZ.k csolkbZV o Hkkjr uo fuekZ.k ,si dk fuekZ.k fd;k x;k gSA rkfd ljdkj dh reke ;kstukvksa dks tu&tu rd igq¡pkus esa ge enn dj ik;sA
</p>
<p class="customeFont">
    Hkkjr] fgUnqLrku] vk;kZorZ ds uke ij dksbZ lekSrk ughaA Hkkjr ds xkSjoe;h bfrgkl dks la;ksx dj j[kus dh] gesa t:jr gS rks flQZ lEeku dhA
</p>
<p class="customeFont" style="font-weight:bold;">vkbZ;s gelc feydj Hkkjr dk u;k fuekZ.k djsa] Hkkjr uo fuekZ.k djsaA
</p>
<p class="customeFont" style="font-weight:900;font-size:25px;">
    oansekrje~A
</p>

BharatNavNirmanWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "भारत नव निर्माण ";
}

<div class="row">
    <div class="col-md-4">
        @Html.Partial("_BnnApp")
    </div>
    <div class="col-md-4">
        @Html.Partial("_BharatMap")
    </div>
    <div class="col-md-4">
        @Html.Partial("_BussinessPartner")
    </div>
</div>
<div class="row">
    <div class="col-md-4">

        @Html.Partial("_ChangeToBharat")
    </div>
    <div class="col-md-4">
        @Html.Partial("_BharatSurvey")
    </div>
    <div class="col-md-4">

    </div>
</div>

BharatNavNirmanWeb/Views/Home/MissionAndVision.cshtml
@{
    ViewBag.Title = "दूरदर्शिता और मिशन";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title </h2>
</hr>
<img src="~/Content/Images/header.gif" />
<p class="customeFont">
    Hkkjr uo fuekZ.k fd ,d lksp gS] fopkj gS ,d u;s Hkkjr ds fuekZ.k dhA ftldk liuk gj yksxk jkst ?kjksa esa cSBdj ns[krs gSA ysfdu vkxs vk;s rks dkSu vk;sa \ 
</p>
<p class="customeFont">
    blh bartkj dks [kRe djrs gq, Hkkjr uo fuekZ.k dk fuekZ.k fd;k x;k gSA Hkkjr uo fuekZ.k ,d IysVQkWeZ gS ftlds ek/;e ls viuk&viuk ;ksxnku ns dj Hkkjr ds izfr viuh ftEesokjh dks fuHkkus dkA Hkkjr uo fuekZ.k ,d fopkj/kkjk ds lkFk Hkkjr ds fgrksa esa dk;Z dj jgh gSA

</p>
<img src="~/Content/Images/bharat-darshan-hindi-magazine-hindi-stories-and-poems.jpg" />
<p class="customeFont" style="font-weight:700;">
    ^^Hkkjr uo fuekZ.k ls eryc ogha gS tks vkidh lksp vkSj fnekx esa vk;kA**

</p>
<p class="customeFont">
    Hkkjr ds izR;sd ukxfjd dh ,d viuh lksp gS ,oa mls fodflr djus ds fy, mUgsa mfpr ekxZn'kZu uk feyus ls mls lgh mi;ksx esa ugha yk ikrs gSaA Hkkjr uo fuekZ.k vkids fy, izR;sd {ks= esa izf'k{k.k dh iw.kZ O;oLFkk ds lkFk&lkFk mfpr O;olk; ,oa ukSdjh ikus Hkh enn djsxhA Hkkjr uo fuekZ.k ,d ,slh lksp dks ysdj vk;k gS fd rkfd Hkkjr ds izR;sd ukxfjd dh iwjh tkudkjh ,d&,d feuV gekjs tuizfrfuf/k;ksa ds ikl gksuk pkfg,A Hkkjr uo fuekZ.k dk iz;kl gS fd Hkkjr ljdkj ,oa jkT;ksa dh ljdkjksa dh reke ;kstukvksa dks ?kj&?kj igq¡pk;k tk ldsA

</p>
<p class="customeFont">
    eq[; :i ls fe'ku dk eq[; vk/kkj gS Hkkjr dh ,drk dks iw.kZ :i ls LoPNrk iw.kZ j[kh tk;saA Hkkjr ds izR;sd ukxfjd ds fy, Hkkjrh; lafo/kku ds vuqlkj ,drk ,oa v[k.Mrk ds fy, izsfjr djuk gSA mudh ewyHkwr lwof/kkvksa dks laoS/kkfud :i ls vke ukxfjdksa rd igq¡pk gSA Hkkjr uo fuekZ.k le; le; ij vius dk;ksZa dh iw.kZ fooj.k csolkbZV ,oa ,si ds ek/;e ls vki lHkh ukxfjdksa dks ,oa gekjs lnL;ksa dks lwpuk bZ&esy ,oa ,si ds ek/;e ls Hkh nsrh jgsxhA

</p>

BharatNavNirmanWeb/Views/Home/आइकॉन.cshtml
@{
    ViewBag.Title = "आइकॉन";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p class="customeFont">
</p>
<p class="customeFont">
</p>

<p class="customeFont">
</p>

<p class="customeFont">
</p>

<p class="customeFont">
</p>

<p class="customeFont">
</p>

<p class="customeFont">
</p>

<p class="customeFont">
</p>

BharatNavNirmanWeb/Views/Home/आवेदन_प्रपत्र.cshtml
@{
    ViewBag.Title = "आवेदन प्रपत्र";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p class="customeFont">
</p>
<p class="customeFont">
</p>

<p class="customeFont">
</p>

<p class="customeFont">
</p>

<p class="customeFont">
</p>

<p class="customeFont">
</p>

<p class="customeFont">
</p>

<p class="customeFont">
</p>

BharatNavNirmanWeb/Views/Home/पुस्तकालय.cshtml
@{
    ViewBag.Title = "पुस्तकालय";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p class="customeFont">

</p>
<p class="customeFont">

</p>
<p class="customeFont">

</p>
<p class="customeFont">

</p>
<p class="customeFont">

</p>
<p class="customeFont">

</p>
<img src="~/Content/Images/Puastakalya.jpg" />
<p class="customeFont">

</p>

BharatNavNirmanWeb/Views/Shared/_BharatMap.cshtml
<h3>भारत का परिचय </h3>
<style>
    .td {
        padding: 5px;
    }
</style>
<table>
    <tr>
        <td>
        <p>@Html.ActionLink("भारत का नक्शा", "भारत_का_मानचित्र", "Map")</p>
        <p>राज्यों का नक्शा</p>
        <p>जिलों का नक्शा</p>
        <p>प्रखंड का नक्शा</p>
        <p>पंचायत का नक्शा</p>
        <p>लोक सभा</p>
        <p>राज्य सभा</p>
        <p>विधानसभा</p>
        <p>विधान परिषद</p>
        <p>जिला प्रशासक</p>
        <p>पंचायती राज व्यवस्था</p>
            </td>
        </tr>
    </table>